import {
  DefinitionModel, DocumentListModel, GroupInformationPartition, InformationRecordModel, PhysicalModel, PhysicalType, SnapshotDb,
  SpatialLocationModel, Subject, SubjectOwnsPartitionElements,
} from "@itwin/core-backend";
import { IModel } from "@itwin/core-common";
import { type CategoryDef, ElementWriter, insertSpatialCategory } from "./demo/builder";
import { buildOperations } from "./demo/operations";
import { buildPid } from "./demo/pid";
import { buildProcess } from "./demo/process";
import { WATER_PLANT_SCHEMA } from "./demo/schema";
import { buildSite } from "./demo/site";

export interface DemoContext {
  db: SnapshotDb;
  w: ElementWriter;
  subjects: { root: string; civil: string; process: string; electrical: string; operations: string };
  models: {
    site: string; process: string; piping: string; electrical: string;
    areas: string; library: string; trains: string; maintenance: string; drawings: string;
  };
  cats: Record<
    "civil" | "landscape" | "fencing" | "buildings" | "tanks" | "pumps" | "motors" | "valves" | "instruments" | "piping" | "electrical" | "areas",
    CategoryDef
  >;
}

export interface DemoSummary {
  elements: number;
  relationships: number;
}

/** Writes "Riverbend Water Treatment Plant", a small but realistic demo iModel. IModelHost must be started. */
export async function createDemoModel(file: string): Promise<DemoSummary> {
  const db = SnapshotDb.createEmpty(file, {
    rootSubject: { name: "Riverbend Water Treatment Plant", description: "Demo iModel generated by InstanceGraph" },
  });
  try {
    await db.importSchemaStrings([WATER_PLANT_SCHEMA]);
    const ctx = setup(db);
    buildSite(ctx);
    buildProcess(ctx);
    buildOperations(ctx);
    buildPid(ctx);
    db.updateProjectExtents(db.computeProjectExtents().extents);
    db.saveChanges();
    return { elements: count(db, "BisCore.Element"), relationships: count(db, "BisCore.ElementRefersToElements") };
  } finally {
    db.close();
  }
}

function count(db: SnapshotDb, cls: string): number {
  return db.withPreparedStatement(`SELECT COUNT(*) FROM ${cls}`, (stmt) => {
    stmt.step();
    return stmt.getValue(0).getInteger();
  });
}

function setup(db: SnapshotDb): DemoContext {
  const root = IModel.rootSubjectId;
  const subjects = {
    root,
    civil: Subject.insert(db, root, "Civil & Site", "Grading, roads, fencing and buildings"),
    process: Subject.insert(db, root, "Process", "Treatment process equipment and piping"),
    electrical: Subject.insert(db, root, "Electrical & Controls", "Motor control and power distribution"),
    operations: Subject.insert(db, root, "Operations", "Process areas, trains, work orders and drawings"),
  };
  const opsPartition = db.elements.insertElement({
    classFullName: GroupInformationPartition.classFullName,
    model: IModel.repositoryModelId,
    parent: new SubjectOwnsPartitionElements(subjects.operations),
    code: GroupInformationPartition.createCode(db, subjects.operations, "Trains"),
  } as any);
  const models = {
    site: PhysicalModel.insert(db, subjects.civil, "Site"),
    process: PhysicalModel.insert(db, subjects.process, "Process Equipment"),
    piping: PhysicalModel.insert(db, subjects.process, "Piping"),
    electrical: PhysicalModel.insert(db, subjects.electrical, "Electrical"),
    library: DefinitionModel.insert(db, subjects.process, "Equipment Library"),
    areas: SpatialLocationModel.insert(db, subjects.operations, "Process Areas"),
    trains: db.models.insertModel({ classFullName: "WaterPlant:OperationsModel", modeledElement: { id: opsPartition } } as any),
    maintenance: InformationRecordModel.insert(db, subjects.operations, "Maintenance"),
    drawings: DocumentListModel.insert(db, subjects.operations, "Drawings"),
  };
  const cats = {
    civil: insertSpatialCategory(db, "Civil", { Ground: "#6a994e", Paving: "#4a4e57", Markings: "#f5f5f5", Concrete: "#d7d3cb" }),
    landscape: insertSpatialCategory(db, "Landscape", { Trunk: "#6d4c41", Foliage: "#2e7d32" }),
    fencing: insertSpatialCategory(db, "Fencing", { Posts: "#90a4ae", Mesh: "#b0bec5" }, { Mesh: 0.65 }),
    buildings: insertSpatialCategory(db, "Buildings", { Walls: "#e8e1d5", Roof: "#5d6d7e", Glazing: "#7fb3d5", Doors: "#8d6e63" }, { Glazing: 0.45 }),
    tanks: insertSpatialCategory(db, "Tanks", { Shell: "#d6dde4", Concrete: "#bfb9ae", Water: "#3a8fd6", Roof: "#9fb3c8", Steelwork: "#78909c" }, { Water: 0.15 }),
    pumps: insertSpatialCategory(db, "Pumps", { Casing: "#1565c0", Base: "#546e7a" }),
    motors: insertSpatialCategory(db, "Motors", { Body: "#2f855a" }),
    valves: insertSpatialCategory(db, "Valves", { Body: "#c62828", Handwheel: "#fdd835" }),
    instruments: insertSpatialCategory(db, "Instruments", { Body: "#fb8c00" }),
    piping: insertSpatialCategory(db, "Piping", {
      RawWater: "#5d7fa3", Settled: "#4db6ac", Filtered: "#4fc3f7", Treated: "#0288d1", Chemical: "#fbc02d", Sludge: "#795548", Supports: "#78909c",
    }),
    electrical: insertSpatialCategory(db, "Electrical", { Panel: "#b0bec5" }),
    areas: insertSpatialCategory(db, "Process Areas", { Boundary: "#9e9e9e" }),
  };
  const w = new ElementWriter(db);
  // Type definitions in the library; physical elements reference them via TypeDefinition.
  const type = (cls: string, name: string, props: Record<string, unknown>) =>
    w.insert(`WaterPlant:${cls}`, models.library, name, { code: PhysicalType.createCode(db, models.library, name), ...props });
  type("PumpType", "Split-case 150 L/s", { manufacturer: "Aquaflo", modelNumber: "SC-150", ratedFlow: 150, ratedPowerKw: 55 });
  type("PumpType", "End-suction 80 L/s", { manufacturer: "Aquaflo", modelNumber: "ES-80", ratedFlow: 80, ratedPowerKw: 30 });
  type("PumpType", "Diaphragm dosing", { manufacturer: "DoseTech", modelNumber: "DD-12", ratedFlow: 0.05, ratedPowerKw: 0.4 });
  type("ValveType", "Butterfly DN300", { manufacturer: "Flowline", modelNumber: "BF-300", pressureClass: "PN16" });
  type("ValveType", "Gate DN200", { manufacturer: "Flowline", modelNumber: "GV-200", pressureClass: "PN16" });
  type("ValveType", "Check DN200", { manufacturer: "Flowline", modelNumber: "CV-200", pressureClass: "PN16" });
  return { db, w, subjects, models, cats };
}
